name: Bug
description: Report a bug in a snippet
labels: ["type/enhancement", "0 - new", "needs triage"]
body:
  - type: checkboxes
    id: existing-issues
    attributes:
      label: Check existing issues
      description: If someone has already opened an issue for what you are requesting, please add a 👍 reaction to the existing issue instead of creating a new one.
      options:
        - label: I have [checked for existing issues](https://github.com/Esri/arcgis-js-vscode-snippets/issues) to avoid duplicates
    validations:
      required: true
  - type: input
    id: snippet-name
    description: Word(s) that display the snippet in IntelliSense
    attributes:
      label: Snippet prefix
    validations:
      required: true
  - type: textarea
    id: bugreport
    attributes:
      label: Bug
      description: Which is the issue with this snippet?
    validations:
      required: true